CREATE DATABASE IF NOT EXISTS ProductosProovedores;
USE ProductosProovedores;

CREATE TABLE PRODUCTOS (
    PRODUCTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO VARCHAR(100) NOT NULL,
    CATEGORIAID INT NOT NULL,
    PROOVEDORID INT NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL
);

CREATE TABLE CATEGORIAS (
    CATEGORIAID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE PROOVEDOR (
    PROOVEDORID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CONTACTOPROOVEDOR VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL
);

ALTER TABLE PRODUCTOS
DROP COLUMN PRECIO;

AlTER TABLE CATEGORIAS MODIFY COLUMN CATEGORIA CHAR(100) NOT NULL;

ALTER TABLE PROOVEDOR
ADD COLUMN DIRECCION VARCHAR(200) NOT NULL;

DESCRIBE PRODUCTOS;
DESCRIBE CATEGORIAS;
DESCRIBE PROOVEDOR;